### ISSUE TITLE
Can't access Sketch preferences once installing Keys

### ISSUE THREAD

**Issue by danburrows** [exevil/Keys-For-Sketch#21]
I can access Keys plugin but no longer have access to the standard preferences.

**Comment by exevil** [comment]
@danburrows: Hey there! Can you please provide a screencast of your issue?

**Comment by danburrows** [comment]
Yeah sure no problem.

[Only able to access Keys.zip](https://github.com/exevil/Keys-For-Sketch/files/1375323/Only.able.to.access.Keys.zip)

**Comment by exevil** [comment]
Thanks a lot. Marvelous bug! Since I can't reproduce it myself I'd ask you to send me your Sketch and macOS versions as well.

Also, It'd be cool if you try to disable all other plugins except Keys and restart Sketch with this configuration. You can do it via `Plugin > Manage Plugins` option since you can't access the Preferences toolbar.

**Comment by danburrows** [comment]
No problem.
![all-plugins-disabled-excluding keys](https://user-images.githubusercontent.com/6170172/31439447-13642a24-ae84-11e7-9bfd-9066deed36dd.png) - interestingly it's now only showing the manage plugins view.

![all-plugin-disabled](https://user-images.githubusercontent.com/6170172/31439414-f818ff10-ae83-11e7-888b-66b9e24c4311.png)

[test.zip](https://github.com/exevil/Keys-For-Sketch/files/1375468/test.zip)

**Comment by exevil** [comment]
And when you're turning Keys off it starting to work again as expected, yup?

**Comment by danburrows** [comment]
No not at all, it just shows Preferences as a completely blank view. 
My initial thoughts were that it's not an issue with the Keys plugin but it only occurred after installing the Keys plugin. Also on restart of Sketch the preference always returns to this:
![screen shot 2017-10-11 at 1 09 26 pm](https://user-images.githubusercontent.com/6170172/31439821-8fe6d848-ae85-11e7-973a-9dd2078b23e9.png)

**Comment by exevil** [comment]
> And when you're turning Keys off it starting to work again as expected, yup?
I meant turning Keys off and restart Sketch, of course. It should show you a blank Preferences window, but top toolbar should be there since Keys didn't execute on launch. Something like this: 

<img width="632" alt="screen shot 2017-10-11 at 14 15 57" src="https://user-images.githubusercontent.com/1979535/31440025-bb008692-ae8e-11e7-835c-baf84ac4f824.png">

Can you confirm it?

**Comment by exevil** [comment]
Think I solved your problem. While preferences window opened press `Cmd+Alt+T`. This is a shortcut for `View > Hide Toolbar` command. :D

**Comment by danburrows** [comment]
Amazing!! thanks, sorry that I've wasted a bit of your time.

Very useful plugin :)

**Comment by exevil** [comment]
No probs. You're welcome.

Thanks and cheers!
