### ISSUE TITLE
Show and manage conflicts

### ISSUE THREAD

**Issue by illustree** [exevil/Keys-For-Sketch#24]
Hi there, really great idea here! also the fact, that it is integrated into settings .... what about some conflicts management? Plugin would show where I have duplicates and propose to fix ... see Plugin-Monster ... something that direction would be awesome

**Comment by exevil** [comment]
Hey there and thanks for the feedback!

Since Keys is kind of a wrapper for the native macOS shortcut management system, its conflict manager only works with shortcuts that have been set by Keys itself.

All other kinds of conflicts, such as a couple of plugin menu items with same shortcut or some original Sketch menus with same shortcut (got that once) are managed by system directly and Keys just got the end values to operate with it on its level. 

So the kind of plugin conflicts micromanagement that you request is not planned for implementation, sorry. 

Best,
VD
