### ISSUE TITLE
Olny "Insert" menu can use Single-character_shortcuts

### ISSUE THREAD

**Issue by ymzuiku** [exevil/Keys-For-Sketch#31]
"Single-character_ shortcuts customization (like Pencil or Vector)"
Olny "Insert" menu can use Single-character_shortcuts, I can't set "Z" to "command+Z" or "C" to "control+C".

**Comment by exevil** [comment]
@ymzuiku: Hello and thanks for the feedback.

Unfortunately, Sketch itself is only allowed to set single-character shortcuts for specific items under insert menu. That's why Keys can only customize these shortcuts.

[Just added](https://github.com/exevil/Keys-For-Sketch#-why-its-not-possible-to-assign-a-single-character-shortcut-to-menu-item-other-than-specific-items-under-the-insert-menu) this case to FAQ.

Thanks again.
