### ISSUE TITLE
Unable to find a command

### ISSUE THREAD

**Issue by okunev** [exevil/Keys-For-Sketch#33]
Sketch 50 renamed some commands. For example, **Sync Styles** were renamed to Update Text Style.

<img width="632" alt="screen shot 2018-05-11 at 10 37 53" src="https://user-images.githubusercontent.com/3657051/39912535-b8587c2c-5507-11e8-9063-4f5a7e3ed006.png">

<img width="380" alt="screen shot 2018-05-11 at 10 38 19" src="https://user-images.githubusercontent.com/3657051/39912575-d6cdf34e-5507-11e8-9ac6-ae8bbbfbf3e5.png">

**Comment by exevil** [comment]
Hey there!

Thanks for the feedback. 

Internally Sketch may not properly draw some menu items prior to their first appearance in menu, that's why the only way to make these kind of menu items configurable with Keys is to manually access it through the app menu first.

I've [updated FAQ](https://github.com/exevil/Keys-For-Sketch/blob/master/README.md#-some-menu-items-arent-shown-in-keys-how-to-fix) with this answer as well.
