### ISSUE TITLE
"Restart Sketch" popup - unsaved data may be lost 

### ISSUE THREAD

**Issue by willowbrae** [exevil/Keys-For-Sketch#8]
Not sure if this ticket is for you or Sketch developers: after updating the plugin I got a popup with only "Restart" button (no "Close" or "Later" etc.). Too bad I turned off Autosave recently.

**Comment by exevil** [comment]
Hey Mariusz!

Your ticket is addressed correctly. I'll add the requested button in the next release. Sorry for the inconvenience. 😐

Cheers!

**Comment by exevil** [comment]
@willowbrae: So you can get the [latest release](https://github.com/exevil/Keys-For-Sketch/releases/tag/0.8.4) where your problem should be solved.

But make sure that you have all your data saved before an installation because you should still get the old alert after. The new one will be applied only after a restart for future updates. 🤷🏽‍♀️
